server:
  port: 8086

spring:
  application:
    name: loan-request-command
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:password123@localhost:27017/loan_request_command?replicaSet=rs0&authSource=admin}
      database: loan_request_command
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.bracits: DEBUG
    org.springframework.amqp: DEBUG