server:
  port: 8087

spring:
  application:
    name: loan-request-query
  
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: loan_request_query
      authentication-database: admin
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:password123}
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.bracits: DEBUG
    org.springframework.amqp: DEBUG